import {test} from 'node:test';import assert from 'node:assert/strict';import * as G from '../assets/watch-game.mjs';
import {readFileSync} from 'node:fs';
test('earned ore pays for upgrades and persists',()=>{let s=G.fresh(1000);for(let i=0;i<30;i++)G.strike(s,1000);assert.equal(s.ore,30);assert.equal(G.buy(s,'pick'),true);assert.equal(s.ore,0);assert.equal(G.buy(s,'crew'),false);assert.equal(G.restore(JSON.stringify(s),1000).pick,1);});
test('offline cap and malformed saves are safe',()=>{let s=G.fresh(1000);s.crew=1;let r=G.restore(s,1000+48*3600000);assert.equal(r.ore,28800*.8);assert.equal(G.restore('invalid',1000).ore,0);assert.equal(G.restore({...s,crew:-10},1000).crew,0);});
test('prepared dispatches use elapsed time, preserve old hunts, and pay once',()=>{let s=G.fresh(1000);s.ore=1000;s.total=1000;s.progress.bag.coal=20;s.progress.crewDeck.cards.coalhand={stars:1,shards:0};G.toggleCrew(s,'coalhand');assert.equal(G.startExpedition(s,5,1000),true);assert.equal(G.startExpedition(s,5,1000),false);s.blocks+=100;assert.equal(G.collectExpedition(s,1000),false);s=G.restore(s,301000);assert.equal(G.collectExpedition(s,301000),true);assert.equal(G.collectExpedition(s,301000),false);assert.equal(s.progress.command.marks,1);assert.equal(G.startExpedition(s,5,301000),true);assert.equal(G.collectExpedition(s,601000),true);assert.equal(s.relics.length,1);s.expedition={minutes:5,targetBlocks:s.blocks+5,reward:200};s=G.restore(s,601000);assert.equal(G.collectExpedition(s,601000),false);s.blocks+=5;assert.equal(G.collectExpedition(s,601000),true);});
test('prestige requires goal and retains permanent progression',()=>{let s=G.fresh();assert.equal(G.prestige(s),false);s.run=100000;s.ore=5000;s.crew=10;s.relics=['Amber Acorn'];s.badges=['first'];assert.equal(G.prestige(s),true);assert.equal(s.ore,0);assert.equal(s.crew,0);assert.equal(s.prestige,1);assert.equal(s.relics.length,1);assert.equal(G.multiplier(s),1.28);});
test('four-hour stream has continuing goals and functional progression',()=>{let s=G.fresh(1000);for(let t=0;t<14400;t++){let now=1000+t*1000;G.tick(s,1,now);if(t%3===0)G.strike(s,now);if(t%20===0)for(let id of ['forge','drill','crew','pick'])G.buy(s,id);G.claim(s);if(!s.expedition)G.startExpedition(s,15,now);G.collectExpedition(s,now);if(s.run>=G.prestigeGoal(s))G.prestige(s,now);}assert.ok(s.total>100000);assert.ok(s.prestige>=1);assert.ok(s.badges.includes('marathon'));assert.ok(G.prestigeGoal(s)>s.run);console.log('4h simulation:',{total:Math.round(s.total),legacy:s.prestige,expeditions:s.expeditions,goal:G.prestigeGoal(s)});});
test('field orders pay once, scale, and survive legacy and old saves',()=>{let s=G.fresh(1000);assert.equal(G.claimOrder(s),false);s.blocks=8;let expected=G.fieldOrder(s).reward;assert.equal(G.claimOrder(s),expected);assert.equal(s.ore,expected);assert.equal(G.claimOrder(s),false);assert.equal(G.fieldOrder(s).progress,0);s.run=100000;G.prestige(s,1000);assert.equal(s.orders,1);assert.equal(s.orderBase,8);assert.equal(G.claimOrder(s),false);const old={...s};delete old.orders;delete old.orderBase;const restored=G.restore(old,1000);assert.equal(restored.orders,0);assert.ok(Number.isFinite(G.fieldOrder(restored).reward));});
test('veins and tactical guardians produce permanent progress without timers or double pay',()=>{let s=G.fresh(1000);G.ensureVeins(s);for(let i=0;i<100;i++)G.mineVein(s,0,1000+i*150,()=>0);assert.ok(s.blocks>=15);assert.equal(G.startGuardian(s),true);const braced=G.advanceGuardian(s,'brace',()=>0);assert.ok(braced);let won;for(let i=0;i<20&&!won;i++)won=G.advanceGuardian(s,'strike',()=>0).won;assert.equal(won,true);assert.equal(s.bossWins,1);assert.equal(G.advanceGuardian(s,'strike'),false);assert.equal(G.startGuardian(s),false);const r=G.restore(s,21000);assert.equal(r.blocks,s.blocks);assert.deepEqual(r.discoveries,s.discoveries);});
test('edited balances are clamped and file import controls stay disabled',()=>{const s=G.fresh(1000);s.total=100;s.run=80;s.ore=9e15;const r=G.restore(s,1000);assert.equal(r.ore,100);assert.equal(r.run,80);const html=readFileSync(new URL('../watch.html',import.meta.url),'utf8'),ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8');assert.doesNotMatch(html,/id="(?:export|import)"/);assert.doesNotMatch(ui,/Hynoe_Deep_Deeper_Save|\.onchange=async/);});
test('visual outpost teaches the loop and links every game category',()=>{const html=readFileSync(new URL('../watch.html',import.meta.url),'utf8'),ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8');for(const room of ['mine','operations','leaderboard','upgrades','frontier','crew','research','expeditions','journal'])assert.match(html,new RegExp(`data-go="${room}"`));for(const art of ['outpost-panorama','operations-stage','mega-drill','leader-stage','leader-list','crew-stage','lab-scene','forge-scene','hunt-scene','legacy-scene-art'])assert.match(html,new RegExp(art));assert.match(html,/id="how-to-play"/);assert.match(html,/START HERE \/ 60-SECOND FIELD GUIDE/);assert.match(html,/id="focus-mode"/);assert.match(ui,/function openRoom\(id\)/);assert.match(ui,/hynoeDeepDeeperGuideV3/);});
test('purpose-first UI explains every click and provides a playable first shift',()=>{const html=readFileSync(new URL('../watch.html',import.meta.url),'utf8'),ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8');for(const id of ['next-action','tap-reward','break-reward','mine-unlocks','starter-steps','system-atlas'])assert.match(html,new RegExp(`id="${id}"|class="${id}"`));for(const phrase of ['EVERY TAP GIVES','BREAK THE VEIN','EVERY VEIN ADVANCES','What does every room do?'])assert.match(html,new RegExp(phrase));assert.match(ui,/left · break/);assert.match(ui,/dataset\.target/);});
test('first shift always identifies the next unfinished lesson',()=>{const s=G.fresh();let status=G.starterStatus(s);assert.equal(status.completed,0);assert.equal(status.next.id,'vein');s.blocks=1;s.pick=1;s.crew=1;s.progress.crewDeck.caches=1;s.progress.crewDeck.cards.mara={stars:1,shards:0};s.progress.crewDeck.active=['mara'];status=G.starterStatus(s);assert.equal(status.completed,5);assert.equal(status.next.id,'guardian');s.bossWins=1;s.progress.surveys=1;status=G.starterStatus(s);assert.equal(status.completed,7);assert.equal(status.next.target,'frontier');});
test('deep drill operations offer immediate choices without duplicate payouts',()=>{const s=G.fresh(1000);assert.equal(G.runOperation(s,'signal'),false);s.blocks=6;let q=G.operationStatus(s);assert.equal(q.ready,true);const signal=G.runOperation(s,'signal');assert.equal(signal.insight,2);assert.equal(signal.intel,4);assert.equal(s.progress.insight,2);assert.equal(s.opsRuns,1);assert.equal(G.runOperation(s,'signal'),false);s.blocks=12;const supply=G.runOperation(s,'supply');assert.equal(supply.material,'copper');assert.ok(s.progress.bag.copper>=8);s.blocks=18;const before=s.ore,ore=G.runOperation(s,'ore');assert.ok(ore.ore>=180);assert.equal(s.ore,before+ore.ore);assert.equal(s.opsRuns,3);const restored=G.restore(JSON.stringify(s),1000);assert.equal(restored.opsRuns,3);assert.equal(restored.opsIntel,4);assert.match(restored.lastOperation,/Rich Seam/);restored.run=G.prestigeGoal(restored);restored.total=Math.max(restored.total,restored.run);assert.equal(G.prestige(restored,1000),true);assert.equal(restored.opsRuns,3);});
test('legend ladder scores real progress and places the player deterministically',()=>{const s=G.fresh();const start=G.legendStatus(s),firstBoard=G.legendBoard(s,'TERRELL');assert.equal(start.tier.name,'Rookie');assert.equal(firstBoard.find(x=>x.you).name,'TERRELL');const firstRank=firstBoard.find(x=>x.you).rank;s.blocks=500;s.depth=120;s.opsRuns=12;s.bossWins=4;s.prestige=2;s.relics=['Amber Acorn','Copper Compass'];s.progress.chapter=5;s.progress.crewDeck.caches=3;const grown=G.legendStatus(s),board=G.legendBoard(s,'TERRELL'),me=board.find(x=>x.you);assert.ok(grown.score>start.score);assert.ok(me.rank<firstRank);assert.ok(['Silver','Gold','Mythic','Founder'].includes(grown.tier.name));assert.equal(board.filter(x=>x.you).length,1);});
test('global leaderboard submits the same bounded metrics used by the local score',()=>{const s=G.fresh();s.blocks=42;s.progress.surveys=3;s.bossWins=2;s.progress.chapter=4;s.prestige=1;s.progress.crewDeck.caches=5;s.opsRuns=7;s.relics=['Amber Acorn'];s.depth=88;const m=G.legendMetrics(s),command=m.blocks*10+m.surveys*80+m.bossWins*180+m.chapter*350+m.prestige*700+m.caches*90+m.operations*60,score=command+m.crewPower*2+m.operations*160+m.relics*500+m.prestige*1200+m.depth*8;assert.equal(score,G.legendScore(s));assert.equal(m.crewCount,0);const html=readFileSync(new URL('../watch.html',import.meta.url),'utf8'),ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8'),config=JSON.parse(readFileSync(new URL('../data/leaderboard-config.json',import.meta.url),'utf8'));assert.match(html,/GLOBAL OUTPOST LADDER/);assert.match(html,/Site-wide Hall of Legends/);assert.match(ui,/hynoeLegendPlayerId/);assert.match(ui,/\/v1\/score/);assert.match(config.endpoint,/^https:\/\//);});
test('crew caches are earned through play, have duplicate upgrades, lineup bonuses, and pity',()=>{const s=G.fresh();s.blocks=12;let pull=G.openCrewCache(s,()=>0);assert.equal(pull.first,true);assert.equal(pull.card.rarity,'common');assert.equal(G.openCrewCache(s,()=>0),false);s.blocks=24;G.openCrewCache(s,()=>0);s.blocks=36;G.openCrewCache(s,()=>0);const id=pull.card.id;assert.equal(s.progress.crewDeck.cards[id].shards,2);assert.equal(G.toggleCrew(s,id),'added');assert.ok(G.crewBonuses(s.progress).strike>1);assert.equal(G.upgradeCrew(s,id).stars,2);for(let n=4;n<=10;n++){s.blocks=n*12;pull=G.openCrewCache(s,()=>0);}assert.ok(['epic','mythic'].includes(pull.card.rarity));const restored=G.restore(JSON.stringify(s));assert.equal(restored.progress.crewDeck.caches,10);assert.deepEqual(restored.progress.crewDeck.active,[id]);});

test('expedition UI explains locked requirements instead of acting broken',()=>{const ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8');assert.match(ui,/function expeditionBlockers\(minutes\)/);assert.match(ui,/Relic hunt locked:/);assert.match(ui,/Ready check · /);assert.match(ui,/b\.disabled=hardLocked/);assert.doesNotMatch(ui,/b\.disabled=!q\.ready/);});

test('cave runs start persist finish and pay once',()=>{let s=G.fresh(1000);assert.equal(G.startSurvey(s,0),false);s.ore=1000;s.total=1000;assert.equal(G.startSurvey(s,0),true);assert.equal(s.ore,900);assert.equal(G.startSurvey(s,0),false);const first=G.advanceSurvey(s,'scout',()=>0);assert.ok(first);assert.equal(s.progress.run.room,2);s=G.restore(JSON.stringify(s),1000);assert.equal(s.progress.run.room,2);assert.ok(G.surveyForecast(s,'scout'));assert.ok(G.advanceSurvey(s,'scout',()=>0));const final=G.advanceSurvey(s,'scout',()=>0);assert.equal(final.ready,true);const before=s.progress.surveys,reward=G.collectSurvey(s);assert.ok(reward.amount>0);assert.equal(s.progress.surveys,before+1);assert.equal(G.collectSurvey(s),false);});
test('cave UI explains locks and live risk',()=>{const ui=readFileSync(new URL('../assets/watch.mjs',import.meta.url),'utf8');assert.match(ui,/function caveBlockers\(index\)/);assert.match(ui,/Cave locked:/);assert.match(ui,/NEXT HAZARD:/);assert.match(ui,/v\.button\.dataset\.ready=String\(gate\.ready\)/);assert.doesNotMatch(ui,/v\.button\.disabled=locked\|\|!!p\.run/);});
