import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{ChatRoom,validateMessage,moderateMessage,signGuestSession} from '../relay/worker.mjs';
class Storage{constructor(){this.map=new Map;this.alarm=null;this.queue=Promise.resolve();}async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async delete(k){this.map.delete(k);}async list(){return this.map;}async getAlarm(){return this.alarm;}async setAlarm(v){this.alarm=v;}transaction(fn){const op=this.queue.then(()=>fn(this));this.queue=op.catch(()=>{});return op;}}
function setup(){const storage=new Storage,env={TURNSTILE_SECRET:'test',IP_SALT:'test',ADMIN_TOKEN:'private-test',SESSION_SECRET:'session-test',CHAT_ENABLED:'true'};return {storage,room:new ChatRoom({storage},env),env};}
const req=(path,b,auth='',ip='192.0.2.1')=>new Request('https://community.test'+path,{method:b?'POST':'GET',headers:{Origin:'https://hynoesmp.com','CF-Connecting-IP':ip,...(auth?{Authorization:auth}:{})},body:b?JSON.stringify(b):undefined});
const adminReq=(path,b)=>req(path,b,'Bearer private-test');
const msg={name:'Viewer',text:'Hello Hynoe!',consent:true};
async function guest(storage,id='actor-1',callsign='Viewer'){const now=Date.now();await storage.put('actor:'+id,{id,callsign,createdAt:now,lastSeen:now});return 'Guest '+await signGuestSession({actorId:id,issuedAt:now,expiresAt:now+60000},'session-test');}

test('commands control characters and links are rejected',()=>{for(const text of ['/op Player','hello\nstop','hello\u00a7a','https://evil.test'])assert.throws(()=>validateMessage({...msg,text}));});
test('ordinary profanity is censored before storage',()=>{const out=moderateMessage('this is fucking wild');assert.equal(out.action,'censor');assert.match(out.text,/f\*+/);});
test('untrusted origins and unauthed moderation rejected',async()=>{assert.equal((await worker.fetch(new Request('https://community.test/messages',{headers:{Origin:'https://evil.test'}}),{})).status,403);const {room}=setup();assert.equal((await room.fetch(req('/admin'))).status,401);});
test('accepted messages are stored directly without external delivery and concurrent send blocked',async()=>{const {room,storage}=setup(),auth=await guest(storage);let external=0;const old=globalThis.fetch;globalThis.fetch=async()=>{external++;throw Error('no external request expected');};try{const body={text:'Hello Hynoe!',consent:true};const responses=await Promise.all([room.fetch(req('/messages',body,auth)),room.fetch(req('/messages',body,auth))]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,429]);assert.equal(external,0);const data=await(await room.fetch(req('/messages'))).json();assert.equal(data.messages.length,1);assert.equal(data.messages[0].ipHash,undefined);assert.equal(data.messages[0].displayName,'Viewer');}finally{globalThis.fetch=old;}});
test('severe content is blocked and never stored',async()=>{const {room,storage}=setup(),auth=await guest(storage);const r=await room.fetch(req('/messages',{text:'k1ll yourself you n1gg3r',consent:true},auth));assert.equal(r.status,400);assert.equal((await(await room.fetch(req('/messages'))).json()).messages.length,0);});
test('wrong Turnstile hostname is rejected during session bootstrap',async()=>{const {room}=setup();const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'evil.test'});try{assert.equal((await room.fetch(req('/session',{token:'bad-host'}))).status,403);}finally{globalThis.fetch=old;}});
test('pause delete mute and expiry cleanup work',async()=>{const {room,storage}=setup(),auth=await guest(storage);await storage.put('messages',[{id:'m',actorId:'actor-1',displayName:'Viewer',text:'hi',ipHash:'private',createdAt:Date.now(),at:Date.now()}]);assert.equal((await room.fetch(adminReq('/admin/pause',{paused:true}))).status,200);assert.equal((await(await room.fetch(req('/messages'))).json()).enabled,false);assert.equal((await room.fetch(req('/messages',{text:'hi',consent:true},auth))).status,429);await room.fetch(adminReq('/admin/delete',{id:'m'}));assert.equal((await storage.get('messages')).length,0);await storage.put('messages',[{at:1,createdAt:1}]);await storage.put('ip:old',{expires:1});await room.alarm();assert.equal((await storage.get('messages')).length,0);assert.equal(await storage.get('ip:old'),undefined);});
test('reports are recorded and mute removes guest history',async()=>{const {room,storage}=setup(),auth=await guest(storage,'actor-bad','Guest');await storage.put('messages',[{id:'bad',actorId:'actor-bad',at:Date.now(),createdAt:Date.now(),ipHash:'guest-hash',displayName:'Guest',text:'abuse'}]);assert.equal((await room.fetch(req('/report',{id:'bad',reason:'abuse'},auth))).status,200);assert.equal((await storage.get('reports')).length,1);assert.equal((await room.fetch(adminReq('/admin/mute',{id:'bad'}))).status,200);assert.ok((await storage.get('mute-actor:actor-bad')).expires>Date.now());assert.equal((await storage.get('messages')).length,0);});
