import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{ChatRoom,validateMessage,moderateMessage} from '../relay/worker.mjs';
class Storage{constructor(){this.map=new Map;this.alarm=null;this.queue=Promise.resolve();}async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async delete(k){this.map.delete(k);}async list(){return this.map;}async getAlarm(){return this.alarm;}async setAlarm(v){this.alarm=v;}transaction(fn){const op=this.queue.then(()=>fn(this));this.queue=op.catch(()=>{});return op;}}
function setup(){const storage=new Storage,env={TURNSTILE_SECRET:'test',IP_SALT:'test',ADMIN_TOKEN:'private-test',SESSION_SECRET:'session-test',CHAT_ENABLED:'true'};return {storage,room:new ChatRoom({storage},env),env};}
const req=(path,b,admin=false,ip='192.0.2.1')=>new Request('https://community.test'+path,{method:b?'POST':'GET',headers:{Origin:'https://hynoesmp.com','CF-Connecting-IP':ip,...(admin?{Authorization:'Bearer private-test'}:{})},body:b?JSON.stringify(b):undefined});
const msg={name:'Viewer',text:'Hello Hynoe!',consent:true,token:'test-token'};

test('commands control characters and links are rejected',()=>{for(const text of ['/op Player','hello\nstop','hello\u00a7a','https://evil.test'])assert.throws(()=>validateMessage({...msg,text}));});
test('ordinary profanity is censored before storage',()=>{const out=moderateMessage('this is fucking wild');assert.equal(out.action,'censor');assert.match(out.text,/f\*+/);});
test('untrusted origins and unauthed moderation rejected',async()=>{assert.equal((await worker.fetch(new Request('https://community.test/messages',{headers:{Origin:'https://evil.test'}}),{})).status,403);const {room}=setup();assert.equal((await room.fetch(req('/admin'))).status,401);});
test('accepted messages are stored directly without external delivery and concurrent send blocked',async()=>{const {room}=setup();let external=0;const old=globalThis.fetch;globalThis.fetch=async url=>{external++;assert.ok(String(url).includes('siteverify'));return Response.json({success:true,hostname:'hynoesmp.com'});};try{const responses=await Promise.all([room.fetch(req('/messages',msg)),room.fetch(req('/messages',msg))]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,429]);assert.equal(external,1);const data=await(await room.fetch(req('/messages'))).json();assert.equal(data.messages.length,1);assert.equal(data.messages[0].ipHash,undefined);assert.equal(data.messages[0].displayName,'Viewer');}finally{globalThis.fetch=old;}});
test('severe content is blocked and never stored',async()=>{const {room}=setup();const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'hynoesmp.com'});try{const r=await room.fetch(req('/messages',{...msg,text:'k1ll yourself you n1gg3r'}));assert.equal(r.status,400);assert.equal((await(await room.fetch(req('/messages'))).json()).messages.length,0);}finally{globalThis.fetch=old;}});
test('wrong Turnstile hostname is rejected',async()=>{const {room}=setup();const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'evil.test'});try{assert.equal((await room.fetch(req('/messages',msg))).status,403);}finally{globalThis.fetch=old;}});
test('pause delete mute and expiry cleanup work',async()=>{const {room,storage}=setup();await storage.put('messages',[{id:'m',displayName:'Viewer',text:'hi',ipHash:'private',createdAt:Date.now(),at:Date.now()}]);assert.equal((await room.fetch(req('/admin/pause',{paused:true},true))).status,200);assert.equal((await(await room.fetch(req('/messages'))).json()).enabled,false);assert.equal((await room.fetch(req('/messages',msg))).status,429);await room.fetch(req('/admin/delete',{id:'m'},true));assert.equal((await storage.get('messages')).length,0);await storage.put('messages',[{at:1,createdAt:1}]);await storage.put('ip:old',{expires:1});await room.alarm();assert.equal((await storage.get('messages')).length,0);assert.equal(await storage.get('ip:old'),undefined);});
test('reports are recorded and mute removes guest history',async()=>{const {room,storage}=setup();const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'hynoesmp.com'});try{await storage.put('messages',[{id:'bad',at:Date.now(),createdAt:Date.now(),ipHash:'guest-hash',displayName:'Guest',text:'abuse'}]);assert.equal((await room.fetch(req('/report',{id:'bad',token:'test'}))).status,200);assert.equal((await storage.get('reports')).length,1);assert.equal((await room.fetch(req('/admin/mute',{id:'bad'},true))).status,200);assert.ok((await storage.get('mute:guest-hash')).expires>Date.now());assert.equal((await storage.get('messages')).length,0);}finally{globalThis.fetch=old;}});
