import {test} from 'node:test';import assert from 'node:assert/strict';import worker,{ChatRoom,validateMessage,commandFor} from '../relay/worker.mjs';
class Storage{constructor(){this.map=new Map;this.alarm=null;this.queue=Promise.resolve();}async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async delete(k){this.map.delete(k);}async list(){return this.map;}async getAlarm(){return this.alarm;}async setAlarm(v){this.alarm=v;}transaction(fn){const op=this.queue.then(()=>fn(this));this.queue=op.catch(()=>{});return op;}}
function setup(){const storage=new Storage,env={BLOOM_API_KEY:'test-only',BLOOM_SERVER_ID:'server',TURNSTILE_SECRET:'test',IP_SALT:'test',ADMIN_TOKEN:'private-test',CHAT_ENABLED:'true'};return {storage,room:new ChatRoom({storage},env),env};}
const req=(path,b,admin=false)=>new Request('https://relay.test'+path,{method:b?'POST':'GET',headers:{Origin:'https://hynoesmp.com','CF-Connecting-IP':'192.0.2.1',...(admin?{Authorization:'Bearer private-test'}:{})},body:b?JSON.stringify(b):undefined});
const msg={name:'Viewer',text:'Hello Hynoe!',consent:true,token:'test-token'};
test('commands and control characters rejected; JSON injection stays plain text',()=>{for(let text of ['/op Player','hello\nstop','hello\u00a7a'])assert.throws(()=>validateMessage({...msg,text}));let m=validateMessage({...msg,text:'"}],"clickEvent":{"action":"run_command","value":"/op x"}'});let c=commandFor(m);let parsed=JSON.parse(c.slice('tellraw @a '.length));assert.equal(parsed[2].text,m.text);assert.equal(parsed[2].clickEvent,undefined);});
test('untrusted origins and unauthed moderation rejected',async()=>{assert.equal((await worker.fetch(new Request('https://relay.test/messages',{headers:{Origin:'https://evil.test'}}),{})).status,403);const {room}=setup();assert.equal((await room.fetch(req('/admin'))).status,401);});
test('accepted messages are stored without exposing visitor hash; concurrent send blocked',async()=>{const {room}=setup();let commands=0;const old=globalThis.fetch;globalThis.fetch=async(url,options)=>{if(url.includes('siteverify'))return Response.json({success:true,hostname:'hynoesmp.com'});commands++;assert.ok(JSON.parse(options.body).command.startsWith('tellraw @a '));return new Response(null,{status:204});};try{const responses=await Promise.all([room.fetch(req('/messages',msg)),room.fetch(req('/messages',msg))]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,429]);assert.equal(commands,1);const data=await(await room.fetch(req('/messages'))).json();assert.equal(data.messages.length,1);assert.equal(data.messages[0].ipHash,undefined);}finally{globalThis.fetch=old;}});
test('Minecraft refusal never becomes a successful feed entry',async()=>{const {room}=setup();const old=globalThis.fetch;globalThis.fetch=async url=>url.includes('siteverify')?Response.json({success:true,hostname:'hynoesmp.com'}):new Response(null,{status:403});try{assert.equal((await room.fetch(req('/messages',msg))).status,502);assert.equal((await(await room.fetch(req('/messages'))).json()).messages.length,0);}finally{globalThis.fetch=old;}});
test('wrong hostname is rejected before Minecraft is contacted',async()=>{const {room}=setup();let calls=0;const old=globalThis.fetch;globalThis.fetch=async()=>{calls++;return Response.json({success:true,hostname:'evil.test'});};try{assert.equal((await room.fetch(req('/messages',msg))).status,403);assert.equal(calls,1);}finally{globalThis.fetch=old;}});
test('pause and delete work and expiry alarm removes old messages',async()=>{const {room,storage}=setup();await storage.put('messages',[{id:'m',name:'Viewer',text:'hi',ipHash:'private',at:Date.now()}]);assert.equal((await room.fetch(req('/admin/pause',{paused:true},true))).status,200);assert.equal((await(await room.fetch(req('/messages'))).json()).enabled,false);assert.equal((await room.fetch(req('/messages',msg))).status,429);await room.fetch(req('/admin/delete',{id:'m'},true));assert.equal((await storage.get('messages')).length,0);await storage.put('messages',[{at:1}]);await storage.put('ip:old',{expires:1});await room.alarm();assert.equal((await storage.get('messages')).length,0);assert.equal(await storage.get('ip:old'),undefined);});
test('reports are recorded and mute removes guest history',async()=>{const {room,storage}=setup();let old=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,hostname:'hynoesmp.com'});try{await storage.put('messages',[{id:'bad',at:Date.now(),ipHash:'guest-hash',name:'Guest',text:'abuse'}]);assert.equal((await room.fetch(req('/report',{id:'bad',token:'test'}))).status,200);assert.equal((await storage.get('reports')).length,1);assert.equal((await room.fetch(req('/admin/mute',{id:'bad'},true))).status,200);assert.ok((await storage.get('mute:guest-hash')).expires>Date.now());assert.equal((await storage.get('messages')).length,0);assert.equal((await storage.get('reports')).length,0);}finally{globalThis.fetch=old;}});
