import type { Metadata } from 'next';
import Link from 'next/link';
import { getPublicBusiness } from '@/data/public-businesses';

export const metadata: Metadata = { title: 'Public listings, corrections & privacy | Hynoe', description: 'How Hynoe handles factual public business listings, source dates, correction requests and ownership review.', robots: { index: false, follow: true } };

type Props = { searchParams: Promise<{ listing?: string | string[] }> };
export default async function ListingPolicy({ searchParams }: Props) {
  const params = await searchParams;
  const listing = typeof params.listing === 'string' ? getPublicBusiness(params.listing) : undefined;
  const section = { marginTop: 36, scrollMarginTop: 30 };
  return <main className="site-shell" style={{ maxWidth: 900, padding: '32px 24px 70px', lineHeight: 1.85 }}>
    <nav aria-label="Hynoe navigation" style={{ display: 'flex', flexWrap: 'wrap', gap: 24, fontSize: 14 }}><Link href="/preview">← Hynoe home</Link><Link href="/search">Explore pages</Link><a href="#corrections">Listing help</a></nav>
    <header style={{ marginTop: 46 }}><p className="eyebrow">Public directory · reviewed October 7, 2026</p><h1 style={{ fontSize: 'clamp(34px,6vw,58px)', lineHeight: 1.08, letterSpacing: '-1.7px' }}>Useful information.<br />Clear boundaries.</h1><p style={{ fontSize: 18 }}>A listing helps you find a business. It does not mean the business joined Hynoe, approved its page, paid for inclusion or endorsed us.</p></header>
    <section style={section}><h2>What these listings contain</h2><p>The starter directory uses business names, official website links, broad categories, brief factual summaries written for Hynoe and, where reviewed, a business-level city. Each outside listing has a source link, review date and visible unclaimed status. We do not copy website descriptions, photos, logos, reviews or private contact details into these listings.</p><p>Information can change. A reviewed source is not a guarantee of quality, safety, licensing, current availability or ownership. Source records older than 90 days are marked for another review; their original review date is not replaced with today’s date.</p></section>
    <section style={section}><h2>Public does not mean unrestricted</h2><p>Hynoe’s directory policy is to use limited factual information from accessible official sources, not to reproduce a business’s copyrighted presentation. We do not bypass logins, paywalls, verification or access restrictions. Bulk imports, licensed datasets and third-party APIs require a separate review of their terms, reuse rights and applicable law before use.</p><p>A business listing is not permission to publish an individual’s home address, personal contact details, likeness, sensitive information or information about children. Public availability is not a blanket exemption from privacy or other legal obligations.</p></section>
    <section style={section}><h2>No borrowed trust</h2><p>Outside directory records are labeled <strong>unclaimed</strong>. There are no customer ratings, review counts, verification badges, partner badges or paid placements on these starter listings. Hynoe-owned projects are shown separately in Hynoe Originals, not presented as independently endorsed businesses.</p><p>The preview’s business cards are editorial starter entries, not a “best businesses” ranking. Search matches the words and categories in the current directory; inclusion and ordering are not purchased. Any future sponsorship must be conspicuously labeled and must not be presented as organic ranking or independent approval.</p></section>
    <section id="corrections" style={{ ...section, border: '1px solid #d5c9ad', borderRadius: 18, padding: 25, background: '#f2ecdf', color: '#463b28' }}>
      <h2 style={{ marginTop: 0 }}>Correction, removal or ownership review</h2>
      {listing ? <p><strong>Selected listing:</strong> <Link href={`/p/${listing.slug}`} style={{ textDecoration: 'underline' }}>{listing.name}</Link><br /><code>/p/{listing.slug}</code></p> : <p>Include the Hynoe listing URL so the team can identify the correct record.</p>}
      <p>The current support route is a <strong>private conversation with the Hynoe owner or moderation team through the official Discord</strong>. The button below opens that community; it does not submit a request, start a private conversation automatically or grant page ownership.</p>
      <a className="primary-cta" href="https://discord.gg/wYTePCkXd5" target="_blank" rel="noopener noreferrer">Open official Hynoe Discord ↗</a>
      <details style={{ marginTop: 22 }}><summary style={{ cursor: 'pointer', fontWeight: 600 }}>What to include in a private request</summary><p>Provide the listing URL, whether you request correction, removal or ownership review, a short explanation, and a public official source supporting the change. Ownership review may require confirmation through the business’s official domain or an independently verified official channel. Do not send passwords, access tokens, recovery codes, payment details or government identification.</p></details>
      <p><strong>Do not post private evidence in public chat or a GitHub issue.</strong> Corrections and removals are not paid services. An ownership request does not transfer control automatically. A verified private support inbox and dedicated request-tracking workflow are still required before this starter directory expands beyond manual review; this page does not claim they already exist.</p>
    </section>
    <section id="privacy" style={section}><h2>Privacy in this preview</h2><p>The business filters on <code>/preview</code> work in your browser and do not send or save their input. The main Search form navigates to a URL containing the search terms; that URL may appear in browser history and hosting logs. Do not use it to enter private or sensitive information.</p><p>This preview does not initialize an advertising tracker, third-party analytics SDK, business website embed or video player. Hosting providers still receive ordinary technical requests. Hynoe artwork loads from hynoesmp.com. Clicking external links opens independent services under their own terms and privacy practices. Search, account pages, CreatorOps and community features have separate processing; this page is not a privacy certification for those products.</p><p>A request you send privately to support is processed to understand and resolve the request. Do not assume that clearing your browser deletes a support message. Ask the team privately about access, correction or deletion of Hynoe-held request information. Applicable legal and security obligations may affect retention.</p></section>
    <section style={section}><h2>Policy references</h2><p>This is an operating policy, not legal advice or a guarantee against claims. The U.S. sources below inform this initial approach. Rules differ by jurisdiction and can change; expanding the directory, collecting owner data, adding reviews or monetizing listings requires further review.</p><p><a href="https://copyright.gov/help/faq/faq-protect.html" target="_blank" rel="noopener noreferrer">U.S. Copyright Office: facts, names and website content ↗</a></p><p><a href="https://www.govinfo.gov/content/pkg/USCODE-2024-title15/html/USCODE-2024-title15-chap22-subchapIII-sec1125.htm" target="_blank" rel="noopener noreferrer">15 U.S.C. § 1125: false affiliation and misleading descriptions ↗</a></p><p><a href="https://www.ftc.gov/business-guidance/resources/consumer-reviews-testimonials-rule-questions-answers" target="_blank" rel="noopener noreferrer">FTC: consumer reviews and testimonials guidance ↗</a></p></section>
    <footer style={{ marginTop: 45, borderTop: '1px solid #d7d2c5', paddingTop: 24, fontSize: 14 }}><Link href="/preview">Return to the Hynoe preview →</Link></footer>
  </main>;
}
